language: node_js
node_js: stable

cache:
  directories:
    - node_modules

env:
  global:
    - GH_REF: github.com/zerosrat/blog-g-test.git

branches:
  only:
  - master

before_install:
  - npm i -g hexo-cli

install:
  - npm i

script:
  - hexo g

after_script:
  - cd public
  - git init
  - git config user.name "zerosrat"
  - git config user.email "zero.yu@hotmail.com"
  - git add --all
  - git commit -m "Update docs via travis"
  - git push --force "https://${GH_TOKEN}@${GH_REF}" master:gh-pages