language: node_js
node_js:
  - "7"

cache:
  directories:
    - node_modules

env:
  global:
    - GH_REF: github.com/zerosrat/blog-g-test.git
    - secure: "CJ+wexqQG5zIoCdMURB7PiGfYx/h2InsMNyaN3vt3PaTMdfJDbx2LFXw+AwE1dKiHok9PRGTR/6ezjpT2SZ1BKdWA+i1qwx3S7pcdncFBaJsNxfot5qdYTQhUaHTTmqdfFTYC8iSoK4j6QDj9GhLLLlOUMqNWYIAwGKEJSFoEWorMbBHVlDT2YB/NLIzNOQsvRtxhkSf+CoHpbAVju5P5bbRqidNiKIHU/4GCHZgeNPIJ7QdqrJ1QA9y3+HMN/+Bik9VMPEM1oUXA3z2Jp8krpDI0rraLxCLm48UPZTrhnQfFWDjuoSRrDjG9nTwUG/FwXmBE31ipxOTmFKNeQyvRxMRMe1X+tm++cHeCTaRefhDy1+Y8suGR0Un50rWFZ7BFIRHEhB7JfPEtITDKbBW8ZeHYE8D3koih4HTx0PLf2MI/SIFZ5FiJbtnBsGFfv/GzWqUvFPy5JmOqSLJ5MBXJQCqGvNutQcWQPL4pTj2BKotsnvIVGQSqIYw4y5PshUZKCJamSXZIFWvpPp68GjNDsDdXWw+TDq/LE+TFiCGNvDc4CCwMp60btNsQtQweSZKHrlsNKqv803mIA8f6ZdbVQ9T9QlKBtjwWebFmzI1ULtF8wgCarBdrGNTFTk9cWlHO/UBFxAKKxAS4sx0HHXagEUgEm0tL8qbgWwACaF2K3Y="
branches:
  only:
  - master

before_install:
  - npm i -g hexo-cli

install:
  - npm i

script:
  - hexo g

after_script:
  - cd public
  - git init
  - git config user.name "zero_ai"
  - git config user.email "zero.yu@hotmail.com"
  - git add --all
  - git commit -m "Update docs via travis"
  - git push -f "https://{GH_TOKEN}@${GH_REF}" master:gh-pages
# E: Build LifeCycle